# Generated by Django 4.1.3 on 2022-12-21 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenPrimaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("No_orden", models.CharField(max_length=50)),
                ("fecha_creacion", models.DateTimeField()),
                ("fecha_entrada_taller", models.DateTimeField(blank=True, null=True)),
                ("folio_venta", models.CharField(blank=True, max_length=80, null=True)),
                ("fecha_venta", models.DateTimeField(blank=True, null=True)),
                ("garantia", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "fecha_vencimiento_garantia",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("servicio", models.CharField(max_length=20)),
                ("serie", models.CharField(max_length=80)),
                ("nombre_cliente_entrega", models.CharField(max_length=120)),
                ("direccion_cliente_entrega", models.CharField(max_length=120)),
                ("ci_cliente_entrega", models.CharField(max_length=20)),
                ("contacto_telefono", models.CharField(max_length=20)),
                ("propietario", models.BooleanField(default=False)),
                ("confComercial", models.BooleanField(default=False)),
                ("confTaller", models.BooleanField(default=False)),
                ("fecha_defectacion", models.DateTimeField(blank=True, null=True)),
                ("accion_reparacion", models.TextField(blank=True, null=True)),
                ("fecha_gestion", models.DateTimeField(blank=True, null=True)),
                (
                    "nombre_cliente",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("impresion", models.BooleanField(default=False)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "nombre_cliente_recibe",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "direccion_cliente_recibe",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "ci_cliente_recibe",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("cerrada", models.BooleanField(default=False)),
                ("garantia_reparacion", models.DateTimeField(blank=True, null=True)),
                ("tiempo", models.IntegerField(blank=True, null=True)),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.centro"
                    ),
                ),
                (
                    "cierra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cierra",
                        to="base.trabajador",
                    ),
                ),
                (
                    "consumo_recursos",
                    models.ManyToManyField(blank=True, to="base.consumo_recursos"),
                ),
                ("defecto", models.ManyToManyField(to="base.defecto")),
                (
                    "entrega",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrega",
                        to="base.trabajador",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.estado"
                    ),
                ),
                (
                    "llama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llama",
                        to="base.trabajador",
                    ),
                ),
                (
                    "mano_obra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.manoobra",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.modelo"
                    ),
                ),
                (
                    "ordena",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordena",
                        to="base.trabajador",
                    ),
                ),
                (
                    "prefijo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.prefijo"
                    ),
                ),
                (
                    "repara",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repara",
                        to="base.trabajador",
                    ),
                ),
                (
                    "tecnologia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.tecnologia",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ordenes",
            },
        ),
        migrations.CreateModel(
            name="ReporteGestionImpreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordenes", models.ManyToManyField(to="Comercial.ordenprimaria")),
                (
                    "reporta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.trabajador",
                    ),
                ),
            ],
        ),
    ]
