# Generated by Django 4.1.3 on 2022-11-28 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo_Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('importe', models.FloatField()),
                ('asociado_orden', models.BooleanField(default=False)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.centro')),
            ],
        ),
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Division_Territorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=300)),
                ('codigo_sap', models.CharField(max_length=60)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('codigo_sap', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPrimaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_orden', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_entrada_taller', models.DateTimeField(blank=True, null=True)),
                ('ordena', models.CharField(blank=True, max_length=60, null=True)),
                ('folio_venta', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_venta', models.DateTimeField(blank=True, null=True)),
                ('garantia', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_vencimiento_garantia', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('servicio', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=80)),
                ('nombre_cliente_entrega', models.CharField(max_length=120)),
                ('direccion_cliente_entrega', models.CharField(max_length=120)),
                ('ci_cliente_entrega', models.CharField(max_length=20)),
                ('contacto_telefono', models.CharField(max_length=20)),
                ('propietario', models.BooleanField(default=False)),
                ('confComercial', models.BooleanField(default=False)),
                ('confTaller', models.BooleanField(default=False)),
                ('entrega', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_defectacion', models.DateTimeField(blank=True, null=True)),
                ('repara', models.CharField(blank=True, max_length=60, null=True)),
                ('accion_reparacion', models.TextField(blank=True, null=True)),
                ('fecha_gestion', models.DateTimeField(blank=True, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=160, null=True)),
                ('impresion', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cierra', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre_cliente_recibe', models.CharField(blank=True, max_length=120, null=True)),
                ('direccion_cliente_recibe', models.CharField(blank=True, max_length=120, null=True)),
                ('ci_cliente_recibe', models.CharField(blank=True, max_length=20, null=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('garantia_reparacion', models.DateTimeField(blank=True, null=True)),
                ('tiempo', models.IntegerField(blank=True, null=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.centro')),
                ('consumo_recursos', models.ManyToManyField(blank=True, to='Taller.consumo_recursos')),
                ('defecto', models.ManyToManyField(to='Taller.defecto')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.estado')),
            ],
            options={
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='Prefijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('codigo_sap', models.CharField(max_length=60)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_siprec', models.CharField(max_length=30)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.centro')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='ReporteGestionImpreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenes', models.ManyToManyField(to='Taller.ordenprimaria')),
                ('reporta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='ordenprimaria',
            name='llama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taller.trabajador'),
        ),
        migrations.AddField(
            model_name='ordenprimaria',
            name='mano_obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taller.manoobra'),
        ),
        migrations.AddField(
            model_name='ordenprimaria',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.modelo'),
        ),
        migrations.AddField(
            model_name='ordenprimaria',
            name='prefijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.prefijo'),
        ),
        migrations.AddField(
            model_name='ordenprimaria',
            name='tecnologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.tecnologia'),
        ),
        migrations.CreateModel(
            name='OrdenHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(blank=True, max_length=60, null=True)),
                ('servicio', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_defectacion', models.DateTimeField()),
                ('accion_reparacion', models.TextField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.centro')),
                ('estado_defectadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.estado')),
                ('orden_reparada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.ordenprimaria')),
            ],
        ),
        migrations.AddField(
            model_name='modelo',
            name='tecnologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.tecnologia'),
        ),
        migrations.AddField(
            model_name='consumo_recursos',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.recursos'),
        ),
        migrations.CreateModel(
            name='Centro_Telecomunicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.division_territorial')),
            ],
        ),
        migrations.AddField(
            model_name='centro',
            name='centro_telecomunicaciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taller.centro_telecomunicaciones'),
        ),
    ]
